### ISSUE TITLE
Myprofle

### ISSUE THREAD

**Issue by eerison** [lifeitech/cv-react#1]
Hello @lifeitech  :) , in case you have sometime.

give a try in [myprofile project](https://github.com/shield-wall/myprofile), you can generate your resume just using yaml sintax in discussion section in github.

in the end, you will generate something like this: https://github.com/shield-wall/myprofile/discussions/723

**Comment by lifeitech** [comment]
> Hello @lifeitech :) , in case you have sometime.
> 
> give a try in [myprofile project](https://github.com/shield-wall/myprofile), you can generate your resume just using yaml sintax in discussion section in github.
> 
> in the end, you will generate something like this: [shield-wall/myprofile#723](https://github.com/shield-wall/myprofile/discussions/723)

Cool!
